Compatibility with nexus 3.38
* upgrade gradle nexus dependencies
* fix java.lang.NoSuchMethodError: org.sonatype.nexus.repository.search.SearchService.searchUnrestricted exception by switching to SearchService.search method
* change data model to nexus 3.38 SearchService.search function model